### ISSUE TITLE
Importing Payload components causes SyntaxError on the front-end

### ISSUE THREAD

**Issue by imCorfitz** [payloadcms/next-payload#45]
I have tried to add a `color-picker` field to a global in Payload, but the moment I call the `useField` hook or `useFieldType` hook, it seems that the front-end is having issues - outputting following in the terminal:

```bash
- error /my-app/node_modules/payload/dist/admin/components/forms/Label/index.scss:1
@import '../../../scss/styles.scss';
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/my-app/node_modules/payload/dist/admin/components/forms/Label/index.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14) {
  digest: undefined
}
```

## How to replicate

1. Spin up a new next installation.
2. Follow the `next-payload` installation directions.
3. Create a `Field.tsx` file in the `payload` directory with following:
```ts
import React from "react";
import { Label } from "payload/components/forms";
import { Props } from "payload/components/fields/Text";

const LabelField: React.FC<Props> = (props) => {
  const { path, required, label } = props;

  return (
    <div>
      <Label htmlFor={path} label={label} required={required} />
    </div>
  );
};

export default LabelField;
```
4. Update `payload.config.ts` as follows:
```ts
import path from "path";
import { buildConfig } from "payload/config";
import Field from "./Field";

export default buildConfig({
  collections: [
    // Your collections here
  ],
  globals: [
    // Your globals here
    {
      slug: "header",
      fields: [
        {
          name: "custom",
          type: "text",
          admin: {
            components: {
              Field,
            },
          },
        },
      ],
    },
  ],
  typescript: {
    outputFile: path.resolve(__dirname, "../payload-types.ts"),
  },
});
```
5. Finally call the `getPayloadClient()` function on the front-end e.g. by updating the default `layout.tsx` file like this:
```ts
import getPayloadClient from '@/payload/payloadClient'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

async function getSiteSettings() {
  const payload = await getPayloadClient();

  return {};
}
```

This will cause the error on the front-end. And if one goes in the the `Field.tsx` file and simply remove the imported `<Label />` component from Payload, then no errors appear.

I have also tried not to use the Payload components, but when I call the `useField()` hook, it causes the same error.

**Comment by imCorfitz** [comment]
I did some further research on the problems this morning, and it is quite clear it is Next.js that messes with it. Creating a clean Next.js with `next-payload` installation with following versions:

```json
"dependencies": {
    "@payloadcms/next-payload": "^0.0.31",
    "@radix-ui/react-slot": "^1.0.2",
    "@types/node": "20.4.2",
    "@types/react": "^18.2.15",
    "@types/react-dom": "^18.2.7",
    "eslint": "8.45.0",
    "eslint-config-next": "13.4.10",
    "next": "13.4.10",
    "payload": "^1.11.2",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "5.1.6"
  },
```

Then I installed the `@payloadcms/plugin-seo` and added the plugin to a clean `payload.config.ts` file:

```ts
 plugins: [
    seo({
      collections: [],
    }),
  ],
```

And it outputted the following errors:

```bash
- error /my-app/node_modules/payload/dist/admin/components/forms/Label/index.scss:1
@import '../../../scss/styles.scss';
^

SyntaxError: Invalid or unexpected token
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1176:20)
    at Module._compile (node:internal/modules/cjs/loader:1218:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/my-app/node_modules/payload/dist/admin/components/forms/Label/index.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/my-app/node_modules/payload/dist/admin/components/forms/field-types/Text/Input.js:8:33)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/my-app/node_modules/payload/dist/admin/components/forms/field-types/Text/index.js:33:33)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/my-app/node_modules/payload/components/forms.js:27:16)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/my-app/node_modules/@payloadcms/plugin-seo/dist/fields/MetaDescription.js:79:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/my-app/node_modules/@payloadcms/plugin-seo/dist/index.js:23:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18) {
  digest: undefined
}
```

**Comment by imCorfitz** [comment]
So basically - If you are using Next.js version `next@13.4.9` and DON'T use custom components that import resources from Payload - then it seems to be working fine. Also with SEO plugin.

**Comment by IAmNatch** [comment]
I was able to resolve this by installing `sass` as a dev dependency of my project. NextJS will transpile saas, but only if saas is installed.

**Comment by lmo-wt** [comment]
This might help you
https://github.com/payloadcms/next-payload/issues/38

**Comment by imCorfitz** [comment]
You are absolutely on the spot mate! 

Freaking spent an entire day trying to figure that out.

And then adding `transpilePackages: ["@payloadcms/plugin-seo"],` to `next.config.js` - otherwise that is gonna break as well. 

Cheers!

**Comment by ToolReaz** [comment]
I still have this issue when importing payload's CodeField component when following the code described [here](https://payloadcms.com/community-help/discord/use-the-value-from-another-field-inside-a-block).

This import is causing the problem:
`import CodeField from "payload/dist/admin/components/forms/field-types/Code";`

But the `payload` package is already added in the `transpilePackages` by the `withPayload` function.

**Comment by imCorfitz** [comment]
@ToolReaz You'll likely have to add `'use client'` to the top of that file.

**Comment by imCorfitz** [comment]
That is likely because your file is ending with `.ts` instead of `.tsx`.

**Comment by IAmNatch** [comment]
Feels like we're so close to a solution here. Unfortunately, if I follow the above process, and use the Payload component inside of a collection field as an admin component, the page displays: "No matched field found for "MyFieldName". 

Example
```typescript
// export-reletionship-field.tsx
"use client"

import RelationshipField from "payload/dist/admin/components/forms/field-types/Relationship/index.js";
export { RelationshipField };

// my-field.ts
import { RelationshipField } from "./export-reletionship-field.tsx";

export const tenant: Field = {
  name: "tenant",
  type: "relationship",
  relationTo: "tenants",
  admin: {
    position: "sidebar",
    components: {
      Field: RelationshipField,
    },
  },
```

If instead I used a non payload component, everything works fine:
```typescript
...
components: {
  Field: () => <div>Hello World</div>
} // Renders as expected on detail screen
...
```

**Comment by imCorfitz** [comment]
I just tried to follow your code example - and it seems to work. Not sure why you get an error saying `No matched field found for "MyFieldName"` as none of these fields are named `MyFieldName`

https://github.com/payloadcms/next-payload/assets/52371939/f5dd49d6-7140-4d2b-923e-09ea3fb6cac6

**Comment by IAmNatch** [comment]
Sorry, I was originally trying to generalize the field name, but in the example I ended up using the actual field. In my case, the error says : "No matched field found for Tenant".

I'll try and create a repro for you this evening.

**Comment by IAmNatch** [comment]
Here's minimal reproduction of the issue, using a `page` relation instead of a `tenant` relation for simplicity:
[next-payload-repro--importing-from-dist.zip](https://github.com/payloadcms/next-payload/files/12365463/next-payload-repro--importing-from-dist.zip)


And here's a video on my end:
https://github.com/payloadcms/next-payload/assets/15078788/3c7e8a34-6735-435c-aef8-2eed3e3267eb



Thanks for your interest in this issue!

**Comment by imCorfitz** [comment]
@IAmNatch I'll agree with you that this is odd.. I did manage to get it to work - but the ways of doing so aren't logical 😵‍💫 Apparently I had to install the seo plugin, transpile it in next config and add the pages collection to the plugin. Then magically, your import of playload fields is working as expected.. 😅

1. `yarn add @payloadcms/plugin-seo`
2. Update next.config.js with following:
```ts
const nextConfig = {
  transpilePackages: ["@payloadcms/plugin-seo"],
};
```
3. Add to the payload config
```ts
import seo from "@payloadcms/plugin-seo";
...
plugins: [
    seo({
      collections: ["pages"],
    }),
  ],
```

**Comment by IAmNatch** [comment]
Weird! I tried this in the repro I shared earlier, but with no luck. I'm not seeing anything in the plugin-seo source code that would affect packaging like this (ie re-exporting of components, or webpack modifications), but perhaps I missed something. Let me know if you'd like another repro.
