### ISSUE TITLE
Error when calling getPayloadClient() in server component (dev)

### ISSUE THREAD

**Issue by lufehr** [payloadcms/next-payload#51]
I have created a fresh Next.js project with `npx create-next-app@latest` (with TypeScript, Tailwind, the App Router and without a src directory) and then applied all the steps from the README. 

When running `npm run dev` I get the following error when calling `getPayloadClient()` from the server component `page.tsx`. 

```
- error TypeError: Cannot read properties of undefined (reading 'sources')
    at Object.<anonymous> (/Users/user1/project1/node_modules/payload/node_modules/swc-minify-webpack-plugin/dist/index.js:38:61)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user1/project1/node_modules/payload/dist/bundlers/webpack/configs/prod.js:9:37)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user1/project1/node_modules/payload/dist/bundlers/webpack/scripts/build.js:8:16)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user1/project1/node_modules/payload/dist/bundlers/webpack/bundler.js:4:17)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user1/project1/node_modules/payload/dist/config/sanitize.js:15:35)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user1/project1/node_modules/payload/dist/config/build.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/user1/project1/node_modules/payload/config.js:1:23)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at payload/config (/Users/user1/project1/.next/server/app/(site)/page.js:209:18) {
  digest: '2670685204'
}
``` 

where `.next/server/app/(site)/page.js:209:18` resolves to the following (last line): 

```javascript
/***/ }),

/***/ "payload/config":
/*!*********************************!*\
  !*** external "payload/config" ***!
  \*********************************/
/***/ ((module) => {

"use strict";
module.exports = require("payload/config"); // <-- HERE: Line 209
``` 

**Environment**

- Mac with M2 chip
- Node version 18.0.0 (also tried with 19.0.0 and the latest Yarn version)
- Npm version 8.6.0
- Payload version 1.11.8
- Next.Js version 13.4.12
- @payloadcms/next-payload version 0.0.33

**Comment by ruslankotliar** [comment]
Met the same issue.

**Comment by lufehr** [comment]
> Met the same issue.

With the same environment?

**Comment by JarrodMFlesch** [comment]
@lufehr & @ruslankotliar I believe this is an NextJS issue. If you update to their canary branch the issue resolves.

Closing for now.
