### ISSUE TITLE
Cannot delete items from any collection

### ISSUE THREAD

**Issue by revnelson** [payloadcms/next-payload#57]
When trying to delete any item from any collection, I'm getting the following error (example error for `carts` collection, but applies to others as well):

```
- error Failed to handle request for /api/carts?where%5Bid%5D%5Bin%5D%5B0%5D=64d89ae73bf13b4917ec939c&locale=en
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at async invokeRequest (/SYSTEM_PATH/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:21:12)
    at async requestHandler (/SYSTEM_PATH/node_modules/next/dist/server/lib/start-server.js:336:33)
    at async Server.<anonymous> (/SYSTEM_PATH/node_modules/next/dist/server/lib/start-server.js:152:13) {
  cause: RequestContentLengthMismatchError: Request body length does not match content-length header
      at write (node:internal/deps/undici/undici:10059:41)
      at _resume (node:internal/deps/undici/undici:10037:33)
      at resume (node:internal/deps/undici/undici:9938:7)
      at connect (node:internal/deps/undici/undici:9927:7) {
    code: 'UND_ERR_REQ_CONTENT_LENGTH_MISMATCH'
  }
}
```

I tried with Node versions 16, 18, and 20, same error on all. Not sure where to begin with this error so if anyone can chime in, that'd be great. I'm using next-payload v0.0.33 and payload v1.13.4 for reference.

**Comment by JarrodMFlesch** [comment]
This happens for you on any collection? Can you try a very simple collection with 1 field? 

Does this happen locally or when deployed?

**Comment by JarrodMFlesch** [comment]
I am going to close this issue since I was not able to replicate and there has been no response. Please comment on this issue if it persists and you can reproduce it. Thanks!
