### ISSUE TITLE
Error: Cannot find module 'payload/dist/bundlers/webpack/configs/base'

### ISSUE THREAD

**Issue by CreateWebGit** [payloadcms/next-payload#77]
I got this error when I try to do "npm run dev":

node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module 'payload/dist/bundlers/webpack/configs/base'
Require stack:
- /Users/kajan/Projekt/testen/node_modules/@payloadcms/next-payload/withPayloadPlugin.js
- /Users/kajan/Projekt/testen/node_modules/@payloadcms/next-payload/index.js
- /Users/kajan/Projekt/testen/next.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at /Users/kajan/Projekt/testen/node_modules/next/dist/server/require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at mod.require (/Users/kajan/Projekt/testen/node_modules/next/dist/server/require-hook.js:64:28)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/Users/kajan/Projekt/testen/node_modules/@payloadcms/next-payload/withPayloadPlugin.js:2:27)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/kajan/Projekt/testen/node_modules/@payloadcms/next-payload/withPayloadPlugin.js',
    '/Users/kajan/Projekt/testen/node_modules/@payloadcms/next-payload/index.js',
    '/Users/kajan/Projekt/testen/next.config.js'
  ]
}

**Comment by ccapndave** [comment]
I also get this after trying to upgrade to Payload 2.0

**Comment by ruchernchong** [comment]
@jmikrut mentioned on Discord that he and his team is working to get Payload 2.0 compatible with the plugin. 

I supposed that this commit might have done it. I have yet to try. 

https://github.com/payloadcms/next-payload/commit/bddcaeabba770bfbfd344ebdc000559a8b14ccc6

**Comment by ccapndave** [comment]
Yup, just tried and the latest commit has fixed this for me (I now have a different problem but will open that as a new issue).

**Comment by JarrodMFlesch** [comment]
This has been resolved, thanks for reporting!
