### ISSUE TITLE
DATABASE_URI environment variable is missing

### ISSUE THREAD

**Issue by braden-godley** [payloadcms/next-payload#81]
After creating a next app with `npx create-next-app@latest` and following the exact steps described in the README in that project, I see this error.

I understand how to work around it in my own project, but I think it would make sense to create some fix so that it really just immediately works after following the README setup guide.

```
Error: DATABASE_URI environment variable is missing
    at eval (webpack-internal:///(api)/./payload/payloadClient.ts:12:11)
    at (api)/./payload/payloadClient.ts (/home/bgodley/git/payload-next-test/.next/server/pages/api/[collection]/init.js:299:13)
    at __webpack_require__ (/home/bgodley/git/payload-next-test/.next/server/webpack-api-runtime.js:30:51)
    at eval (webpack-internal:///(api)/./node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js:2:21)
    at (api)/./node_modules/@payloadcms/next-payload/dist/middleware/withPayload.js (/home/bgodley/git/payload-next-test/.next/server/vendor-chunks/@payloadcms.js:57:9)
    at __webpack_require__ (/home/bgodley/git/payload-next-test/.next/server/webpack-api-runtime.js:30:51)
    at eval (webpack-internal:///(api)/./node_modules/@payloadcms/next-payload/dist/handlers/[collection]/init.js:12:39)
    at (api)/./node_modules/@payloadcms/next-payload/dist/handlers/[collection]/init.js (/home/bgodley/git/payload-next-test/.next/server/vendor-chunks/@payloadcms.js:22:9)
    at __webpack_require__ (/home/bgodley/git/payload-next-test/.next/server/webpack-api-runtime.js:30:51)
    at eval (webpack-internal:///(api)/./pages/api/[collection]/init.ts:6:112)
    at (api)/./pages/api/[collection]/init.ts (/home/bgodley/git/payload-next-test/.next/server/pages/api/[collection]/init.js:287:13)
    at __webpack_require__ (/home/bgodley/git/payload-next-test/.next/server/webpack-api-runtime.js:30:51)
    at eval (webpack-internal:///(api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2F%5Bcollection%5D%2Finit&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2F%5Bcollection%5D%2Finit.ts&middlewareConfigBase64=e30%3D!:11:87)
    at (api)/./node_modules/next/dist/build/webpack/loaders/next-route-loader/index.js?kind=PAGES_API&page=%2Fapi%2F%5Bcollection%5D%2Finit&preferredRegion=&absolutePagePath=.%2Fpages%2Fapi%2F%5Bcollection%5D%2Finit.ts&middlewareConfigBase64=e30%3D! (/home/bgodley/git/payload-next-test/.next/server/pages/api/[collection]/init.js:281:13)
    at __webpack_require__ (/home/bgodley/git/payload-next-test/.next/server/webpack-api-runtime.js:30:51)
  3 | 
  4 | if (!process.env.DATABASE_URI) {
> 5 |   throw new Error('DATABASE_URI environment variable is missing')
    |        ^
  6 | }
  7 | 
  8 | if (!process.env.PAYLOAD_SECRET) {
```

**Comment by JarrodMFlesch** [comment]
Hey @braden-godley just released a new version that fixes this issue, thanks for reporting!
