### ISSUE TITLE
Builds dont work with next14

### ISSUE THREAD

**Issue by seripap** [payloadcms/next-payload#92]
Running `next build` doesn't work with this package when using next14.

```
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at parse (/Users/local/workspace/app/node_modules/next/dist/compiled/micromatch/index.js:15:9078)
    at Function.picomatch.makeRe (/Users/local/workspace/app/node_modules/next/dist/compiled/micromatch/index.js:15:21670)
    at picomatch (/Users/local/workspace/app/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
    at /Users/local/workspace/app/node_modules/next/dist/compiled/micromatch/index.js:15:19294
    at Array.map (<anonymous>)
    at picomatch (/Users/local/workspace/app/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
    at micromatch.isMatch (/Users/local/workspace/app/node_modules/next/dist/compiled/micromatch/index.js:15:1090)
    at serverIgnoreFn (/Users/local/workspace/app/node_modules/next/src/build/collect-build-traces.ts:321:23)
    at shouldIgnore (/Users/local/workspace/app/node_modules/next/src/build/collect-build-traces.ts:42:7)
   Finalizing page optimization  .   Collecting build traces  .
```

Deps
```
    "next": "^14.0.1",
    "@payloadcms/bundler-webpack": "^1.0.3",
    "@payloadcms/db-mongodb": "^1.0.5",
    "@payloadcms/next-payload": "^0.1.7",
    "@payloadcms/plugin-cloud-storage": "^1.1.1",
    "@payloadcms/plugin-seo": "^1.0.15",
    "@payloadcms/richtext-lexical": "^0.1.16",
    "@payloadcms/richtext-slate": "^1.0.5",
    "payload": "^2.0.12",
```

**Comment by augustgaukstad** [comment]
Also facing this issue after doing a bare minimum next-payload setup. The project builds fine as soon as I downgrade Next by running "npm install next@13".

**Comment by JarrodMFlesch** [comment]
This has been resolved and will be fixed in the next release! Thanks for reporting 👍

**Comment by david-mcbacon** [comment]
> This has been resolved and will be fixed in the next release! Thanks for reporting 👍

Hi @JarrodMFlesch I ran into the same issue with next 14 even when updated to version `0.1.10`. I tried the bare minimum nextjs starter application `npx create-next-app@latest`. `next-build` works fine when downgrading to next 13. 

```
  "dependencies": {
    "@payloadcms/bundler-webpack": "^1.0.5",
    "@payloadcms/db-postgres": "^0.1.13",
    "@payloadcms/next-payload": "^0.1.10",
    "@payloadcms/richtext-slate": "^1.2.0",
    "next": "14.0.3",
    "payload": "^2.2.2",
    "react": "^18",
    "react-dom": "^18"
  },
  ```

**Comment by JarrodMFlesch** [comment]
Interesting, I just spun up a fresh next app and built it right after with the following packages:

```ts
"dependencies": {
  "@payloadcms/bundler-webpack": "^1.0.5",
  "@payloadcms/db-mongodb": "^1.0.8",
  "@payloadcms/next-payload": "^0.1.10",
  "@payloadcms/richtext-slate": "^1.2.0",
  "next": "14.0.3",
  "payload": "^2.2.2",
  "react": "^18",
  "react-dom": "^18"
}
  ```

**Comment by david-mcbacon** [comment]
@JarrodMFlesch yes, I can confirm that build works properly with mongodb, so the problem is postgres package. Should I create a new issue?

**Comment by JarrodMFlesch** [comment]
@david-mcbacon no its all good, I fixed it and will publish a release later today.
