### ISSUE TITLE
Incompatability with lexical editor

### ISSUE THREAD

**Issue by otomir23** [payloadcms/next-payload#96]
I have the following config:
```ts
import {webpackBundler} from '@payloadcms/bundler-webpack';
import {lexicalEditor} from "@payloadcms/richtext-lexical";

export default buildConfig({
    // ...
    admin: {
        bundler: webpackBundler()
    },
    editor: lexicalEditor({}),
    collections: [
         // one or multiple collections with richText field
    ],
    // ...
})
```

and the following page:
```ts
import getPayloadClient from "@/payload/payloadClient";

export default async function Page() {
    const payload = await getPayloadClient();
    // ...
}
```

Opening it results in this error:
```
 ⨯ node_modules\@lexical\react\LexicalComposerContext.dev.js (18:50) @ createContext
 ⨯ createContext only works in Client Components. Add the "use client" directive at the top of the file to use it. Read more: https://nextjs.org/docs/messages/context-in-server-component
    at eval (webpack-internal:///(rsc)/./node_modules/@lexical/react/LexicalComposerContext.dev.js:14:56)
    at (rsc)/./node_modules/@lexical/react/LexicalComposerContext.dev.js (project\.next\server\vendor-chunks\@lexical.js:760:1)
    at __webpack_require__ (project\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@lexical/react/LexicalComposerContext.js:7:40)
    at (rsc)/./node_modules/@lexical/react/LexicalComposerContext.js (project\.next\server\vendor-chunks\@lexical.js:770:1)
    at __webpack_require__ (project\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/richtext-lexical/dist/field/features/debug/TestRecorder/plugin/index.js:19:33)
    at (rsc)/./node_modules/@payloadcms/richtext-lexical/dist/field/features/debug/TestRecorder/plugin/index.js (project\.next\server\vendor-chunks\@payloadcms.js:2220:1)
    at __webpack_require__ (project\.next\server\webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/@payloadcms/richtext-lexical/dist/field/features/debug/TestRecorder/index.js:11:17) {
  type: 'TypeError',
  page: '/page'
}
```

**Comment by otomir23** [comment]
Looks like this was fixed in `@payloadcms/richtext-lexical@0.2.0`
